# Generated by Django 4.2.1 on 2023-05-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('peso_min', models.FloatField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('observaciones', models.CharField(max_length=200)),
                ('empleado', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.CharField(max_length=100)),
                ('pastel_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pastel.pastel')),
            ],
            options={
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
