# Generated by Django 4.2.1 on 2023-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='pastel_id',
            new_name='pastel',
        ),
        migrations.AddField(
            model_name='orden',
            name='precio',
            field=models.FloatField(default=1000),
        ),
    ]
