# Generated by Django 4.2.1 on 2023-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_rename_pastel_id_orden_pastel_orden_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orden',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
