# Generated by Django 4.2.1 on 2023-05-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_alter_orden_empleado_alter_orden_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='cantidad',
        ),
    ]
