# Generated by Django 4.2.1 on 2023-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_rename_horno_id_produccion_horno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
    ]
