# Generated by Django 4.2.1 on 2023-05-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden', '0001_initial'),
        ('empleado', '0004_alter_decorador_options_alter_pastelero_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orden.orden')),
                ('pastelero_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.pastelero')),
            ],
            options={
                'verbose_name_plural': 'Juntas',
            },
        ),
    ]
