# Generated by Django 4.2.1 on 2023-05-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorador',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pastelero',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
