# Generated by Django 4.2.1 on 2023-05-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoracion', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoracion',
            old_name='decorador_id',
            new_name='decorador',
        ),
        migrations.RenameField(
            model_name='decoracion',
            old_name='produccion_id',
            new_name='produccion',
        ),
    ]
